name: ROS2-humble Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: setup ROS2
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    - name: build
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: icm_20948 serial
        target-ros2-distro: humble
        vcs-repo-file-url: "${{ github.workspace }}/icm_20948.rosinstall"
        skip-tests: true
